### ISSUE TITLE
Add Twitter/ Mastodon feed

### ISSUE THREAD

**Issue by GLD5000** [GLD5000/GLD-London-Data-Week#44]

**Comment by SamANutt** [comment]
For the Twitter feed:
If we could have it as a Twitter feed for the @LondonDataWeek, 

- which on the page is about the size of the current 'Get in Touch' section, 
- perhaps framed in a colour from the brand kit, 
- with a title saying 'Here's the latest from us'
- shows retweets and the pinned tweet. 
- shows 4/5 tweets in chronological order
- shows media from the tweet

**Comment by GLD5000** [comment]
Awaiting URL once content is in place

**Comment by GLD5000** [comment]
![image](https://github.com/GLD5000/GLD-London-Data-Week/assets/33987109/f300dc20-0ebd-47db-ab58-b291986f29eb)

**Comment by GLD5000** [comment]
As above, hidden for now - once there is content, just let me know!
