### ISSUE TITLE
Explore way to represent multi-day events

### ISSUE THREAD

**Issue by dingaaling** [GLD5000/GLD-London-Data-Week#53]

**Comment by GLD5000** [comment]
Multi day events will be written into eventdata.tsv e.g.:


Name | Organiser | Date | Time | EventType | MoreInfo | Location
-- | -- | -- | -- | -- | -- | --
London Data Today & Tomorrow Day 1 | GLA | 6/3/2023 | 10:00 - 16:00 | Public Conversations | https://www.eventbrite.com/e/london-data-week-2023-tickets-618137193986 | City Hall
London Data Today & Tomorrow Day 2 | GLA | 7/3/2023 | 10:00 - 16:00 | Public Conversations | https://www.eventbrite.com/e/london-data-week-2023-tickets-618137193987 | City Hall

@dingaaling
