### ISSUE TITLE
Update event info

### ISSUE THREAD

**Issue by dingaaling** [GLD5000/GLD-London-Data-Week#57]
Jen to update event info by uploading new .tsv file

https://docs.google.com/spreadsheets/d/1eVJLJ7ht23mVm5KPvuE66pk78u3Ox1P3F2x4oU99x34/edit?usp=sharing

**Comment by dingaaling** [comment]
Open q: is "production" the repo on the ldw github and will we be able to update the .tsv there to trigger updates?

**Comment by GLD5000** [comment]
> Open q: is "production" the repo on the ldw github and will we be able to update the .tsv there to trigger updates?

That is correct:
Development: [GLD-London-Data-Week](https://github.com/GLD5000/GLD-London-Data-Week)
Production: [ldw23](https://github.com/londondataweek/ldw23)

Commiting anything to either will trigger a push to its respective hosting on Vercel. 

For this reason, it might be a good idea to add data validation to the google sheet data rows and protect the header row.

Anything that breaks the website will not replace the Vercel deployment but a mistake in the .tsv may very well not break the site and could go to production.

Hope that all makes sense!
